# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llm-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 11434
        hostPort: 11434
        protocol: TCP
    # Resource specifications for the node
    kubeadmConfigPatches:
      - |
        kind: NodeRegistration
        kubeletExtraArgs:
          system-reserved: memory=2Gi,cpu=1
          eviction-hard: memory.available<1Gi

# Minimum recommended resources for 1.5B parameter model:
# - RAM: 8GB minimum (12-16GB recommended)
# - CPU: 4 cores minimum
# - Storage: 20GB minimum
