{{- if .Values.openwebui.enabled }}
# We'll use the Helm chart directly, not through Flux CD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: {{ .Values.namespace.name }}
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_BASE
          value: {{ .Values.openwebui.config.OPENAI_API_BASE }}
        - name: OPENAI_API_KEY
          value: {{ .Values.openwebui.config.OPENAI_API_KEY }}
        - name: MODEL
          value: {{ .Values.openwebui.config.MODEL }}

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: {{ .Values.namespace.name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: open-webui
{{- end }}